config/routes.rb
Rails.application.routes.draw do
  resources :avalon_items
  resources :avalon_item_notes, only: [:new, :create]
  resources :people
  resources :performances
  resources :performance_notes, only: [:new, :create]
  resources :policies
  resources :recording_contributors
  resources :recording_notes, only: [:new, :create]
  resources :recordings
  resources :tracks
  resources :contracts

  get '/nav/search', to: 'nav#search', as: "search"
  get '/date_search', to: 'nav#date_search_get', as: 'date_search_get'
  post '/date_search', to: 'nav#date_search_post', as: 'date_search_post'

  get '/nav/test', to: 'nav#test', as: 'nav_test'
  get '/user_guide', to: 'nav#user_guide', as: 'user_guide'
  get '/atom_tester/search', to: 'atom_feed_reader#search', as: 'atom_feed_search'

  get '/atom_tester', to: 'atom_feed_reader#index', as: 'atom_feed_tester'
  get '/atom_tester/json/:id', to: 'atom_feed_reader#read_json', as: 'atom_feed_read_json'
  get '/atom_tester/load_avalon_record/:id', to: 'atom_feed_reader#load_avalon_record', as: 'load_avalon_record'

  get '/people/new/entity/', to: 'people#new_entity', as: 'new_entity'

  get '/services/access_decisions_tester', to: 'test#test_access_decisions', as: 'test_access_decisions'
  get '/services/access_determination/:avalon_identifier', to: 'services#access_determination', as: 'access_determination'

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signoutg', to: 'sessions#destroy', via: :get

  resources :sessions, only: [:new, :destroy] do
    get :validate_login, on: :collection
  end

  get '/users/', to: 'user#index', as: 'users'
  get '/user/ldap_lookup', to: 'user#ldap_lookup', as: 'ldap_lookup'

  resources :works

  post '/avalon_items/access_decision', to: 'avalon_items#ajax_post_access_decision', as: 'ajax_avalon_item_access_decision'
  post '/avalon_items/ajax_needs_review', to: 'avalon_items#ajax_post_needs_review', as: 'ajax_post_needs_review'
  post '/avalon_items/ajax_reviewed', to: 'avalon_items#ajax_post_reviewed', as: 'ajax_post_reviewed'
  get '/avalon_items/ajax/calced_access_determination/:id', to: 'avalon_items#ajax_calced_access', as: 'ajax_avalon_item_calced_access'
  get '/avalon_items/cm/cm_all', to: 'avalon_items#cm_all_items', as: 'avalon_all_cm_items'
  get '/avalon_items/cm/cm_iu_default_only', to: 'avalon_items#cm_iu_default_only', as: 'avalon_items_cm_iu_default_only'
  get '/avalon_items/cm/cm_waiting_on_cl', to: 'avalon_items#cm_waiting_on_cl', as: 'avalon_items_cm_waiting_on_cl'
  get '/avalon_items/cm/cm_waiting_on_self', to: 'avalon_items#cm_waiting_on_self', as: 'avalon_items_cm_waiting_on_self'
  get '/avalon_items/cm/cm_access_determined', to: 'avalon_items#cm_access_determined', as: 'avalon_items_cm_access_determined'
  get '/avalon_items/cm/cm_published', to: 'avalon_items#cm_published', as: 'avalon_items_cm_published'

  get '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder', as: 'ajax_people_adder_get'
  post '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder_post', as: 'ajax_people_adder_post'
  get '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter', as: 'ajax_people_setter_get'
  post '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter_post', as: 'ajax_people_setter_post'
  get '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter', as: 'ajax_work_setter_get'
  post '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter_post', as: 'ajax_work_setter_post'
  get '/ajax/people/ajax_work_person_form', to: "people#ajax_work_person_form", as: 'ajax_work_person_form'

  get '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder', as: 'ajax_work_adder_get'
  post '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder_post', as: 'ajax_work_adder_post'
  post 'avalon_items/:id/ajax_add_note', to: 'avalon_items#ajax_add_note', as: 'ajax_avalon_item_add_note'

  get '/avalon_items/ajax/cl_all', to: 'avalon_items#ajax_all_cl_items', as: 'ajax_avalon_cl_all'
  get '/avalon_items/ajax/cl_initial_review', to: 'avalon_items#ajax_cl_initial_review', as: 'avalon_items_cl_initial_review'
  get '/avalon_items/ajax/cl_waiting_on_cm', to: 'avalon_items#ajax_cl_waiting_on_cm', as: 'avalon_items_cl_waiting_on_cm'
  get '/avalon_items/ajax/cl_waiting_on_self', to: 'avalon_items#ajax_cl_waiting_on_self', as: 'avalon_items_cl_waiting_on_self'
  get '/avalon_items/ajax/cl_access_determined', to: 'avalon_items#ajax_cl_access_determined', as: 'avalon_items_cl_access_determined'

  get '/collections/', to: "collections#index", as: 'collections_index'
  post '/collections/', to: "collections#assign_access", as: 'collection_assign'
  get '/collection/', to: "collections#collection_list", as: "collection_list"

  get '/contracts/ajax/new/:ai_id', to: 'contracts#ajax_new', as: 'ajax_new_contract'
  post '/contracts/ajax/create', to: 'contracts#ajax_create', as: 'ajax_create_contract'
  get '/contracts/ajax/edit/:id', to: 'contracts#ajax_edit', as: 'ajax_edit_contract'
  post '/contracts/ajax/update', to: 'contracts#ajax_update', as: 'ajax_update_contract'
  get '/contracts/ajax/show/:id', to: 'contracts#ajax_show', as: 'ajax_show_contract'

  get 'recordings/ajax/edit/:id', to: 'recordings#ajax_edit', as: 'ajax_edit_recording'
  get 'recordings/ajax/show/:id', to: 'recordings#ajax_show', as: 'ajax_show_recording'

  get '/people/ajax/new', to: 'people#ajax_new_person', as: 'ajax_new_person'
  get '/people/ajax/autocomplete', to: 'people#ajax_autocomplete', as: 'people_ajax_autocomplete'
  get '/people/ajax/autocomplete_company', to: "people#ajax_autocomplete_company", as: "people_ajax_autocomplete_company"
  get '/people/ajax/edit/:id', to: 'people#ajax_edit_person', as: 'ajax_edit_person'

  get '/performances/ajax/new/:recording_id', to: 'performances#ajax_new_performance', as: 'ajax_new_performance'
  get '/performances/ajax/edit/:id', to: 'performances#ajax_edit_performance', as: 'ajax_edit_performance'
  get '/performances/ajax/show/:id', to: 'performances#ajax_show_performance', as: 'ajax_Show_performance'
  post '/performances/ajax/access_determination', to: 'performances#ajax_access_determination', as: 'ajax_performance_access_determination'

  get '/tracks/ajax/new/:performance_id', to: 'tracks#ajax_new_track', as: 'ajax_new_track'
  get '/tracks/ajax/edit/:track_id', to: 'tracks#ajax_edit_track', as: 'ajax_edit_track'
  post '/tracks/ajax/access_determination', to: 'tracks#ajax_access_determination', as: 'ajax_track_access_determination'

  post '/users/ajax/set_user_unit/:username/:unit/:access', to: 'user#ajax_set_user_unit', as: 'ajax_set_user_unit'
  post '/users/ajax/set_user_cl/:username', to: 'users#ajax_toggle_cl', as: 'ajax_set_user_cl'
  get '/works/ajax/new', to: 'works#ajax_new_work', as: 'ajax_new_work'
  get '/works/ajax/:id', to: 'works#ajax_show', as: 'ajax_show_work'
  get '/work/ajax/autocomplete_title', to: 'works#ajax_autocomplete_title', as: 'work_ajax_autocomplete_title'
  get '/work/ajax/edit/:id', to: 'works#ajax_edit_work', as: 'ajax_edit_work'

  root 'nav#start'

end

app/models/recording.rb
class Recording < ApplicationRecord
  include AccessDeterminationHelper

  has_many :recording_performances, dependent: :destroy
  has_many :recording_notes, dependent: :destroy
  has_many :performances, through: :recording_performances, dependent: :destroy

  # this one is wonky because recording_contributor_people holds the role booleans (producer and depositor). A Person only
  # contributes if a role is set. But the RecordingContributorPerson can exist with any roles being set to true so we have
  # to abstract the actual people through the middle query of :contributors
  has_many :recording_contributor_people
  has_many :contributors, -> { where "recording_producer = true OR recording_depositor = true" }, class_name: "RecordingContributorPerson"
  has_many :people, through: :contributors

  after_destroy :killed


  belongs_to :atom_feed_read
  belongs_to :avalon_item
  has_one :pod_physical_object, class_name: 'PodPhysicalObject', foreign_key: 'mdpi_barcode', primary_key: 'mdpi_barcode'
  has_one :pod_unit, through: :pod_physical_object

  accepts_nested_attributes_for :recording_notes, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :performances

  before_save :edtf_dates

  after_save :update_avalon_items

  UNITS = ["B-AAAI", "B-AAAMC", "B-AFRIST", "B-ALF", "B-ANTH", "B-ARCHIVES", "B-ASTR", "B-ATHBASKM", "B-ATHBASKW",
           "B-ATHFHOCKEY", "B-ATHFTBL", "B-ATHROWING", "B-ATHSOCCM", "B-ATHSOFTB", "B-ATHTENNM", "B-ATHVIDEO",
           "B-ATHVOLLW", "B-ATM", "B-BCC", "B-BFCA", "B-BUSSPEA", "B-CAC", "B-CDEL", "B-CEDIR", "B-CELCAR", "B-CELTIE",
           "B-CEUS", "B-CHEM", "B-CISAB", "B-CLACS", "B-CMCL", "B-CREOLE", "B-CSHM", "B-CYCLOTRN", "B-EASC", "B-EDUC",
           "B-EPPLEY", "B-FACILITY", "B-FINEARTS", "B-FOLKETHNO", "B-FRANKLIN", "B-GBL", "B-GEOLOGY", "B-GLBTSSSL",
           "B-GLEIM", "B-GLOBAL", "B-HPER", "B-IAS", "B-IAUNRC", "B-IPRC", "B-IUAM", "B-IULMIA", "B-JOURSCHL", "B-KINSEY",
           "B-LACASA", "B-LAW", "B-LIBERIA", "B-LIFESCI", "B-LILLY", "B-LING", "B-MATHERS", "B-MDP", "B-MUSBANDS", "B-MUSIC",
           "B-MUSOPERA", "B-MUSREC", "B-OID", "B-OPTMSCHL", "B-OPTOMTRY", "B-POLISH", "B-PSYCH", "B-RECSPORTS", "B-REEI",
           "B-RTVS", "B-SAGE", "B-SAVAIL", "B-SWAIN", "B-TAI", "B-THTR", "B-UNDRWATR", "B-UNIVCOMM", "B-WELLS", "B-WEST",
           "EA-ARCHIVES", "EA-ATHL", "I-ARCHIVES", "I-DENT", "I-LIBR-SCA", "I-RAYBRAD", "KO-ARCHIVES", "NW-ARCHIVES",
           "SB-ARCHIVES", "SB-PHYS", "SB-ULIB", "SE-ARCHIVES"]

  validates :access_determination, :inclusion => {:in => ACCESS_DECISIONS}

  def contributors
    people.map { |p| p.name }
  end

  def edtf_dates
    # copyright end date
    date = Date.edtf(copyright_end_date_text.gsub('/', '-'))
    self.copyright_end_date = date
    puts "Set copyright_end_date to #{date}, calling self.copyright_end_date: #{self.copyright_end_date}"

    # creation date
    date = Date.edtf(creation_date_text.gsub('/', '-'))
    self.creation_date = date
    #puts "Set creation_date to #{date}, calling self.creation_date: #{self.creation_date}"

    # date of first pub
    date = Date.edtf(date_of_first_publication_text.gsub('/', '-'))
    self.date_of_first_publication = date
    #puts "Set date_of_first_publication to #{date}, calling self.date_of_first_publication: #{self.date_of_first_publication}"
  end

  private
  def update_avalon_items
    avalon_item.update(structure_modified: true)
  end

  def killed
    puts "#{self.class}:#{self.id} destroyed!"
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: [:show, :edit, :update, :destroy, :mark_needs_review, :mark_reviewed]


  # GET /recordings
  # GET /recordings.json
  def index
    @avalon_items = AvalonItem.where(pod_unit: UnitsHelper.human_readable_units_search(User.current_username)).order(:title)
  end

  # GET /recordings/1
  # GET /recordings/1.json
  # def show
  #   if User.belongs_to_unit?(@recording.unit)
  #     render :show
  #   else
  #     render 'recordings/not_authorized'
  #   end
  # end

  def ajax_show
    recording = Recording.find(params[:id])
    @avalon_item = recording.avalon_item
    render partial: 'recordings/ajax_show', locals: {recording: recording}
  end

  # GET /recordings/new
  def new
    @recording = Recording.new
  end

  # GET /recordings/1/edit
  def edit
    render 'recordings/not_authorized' unless User.belongs_to_unit?(@recording.unit)
  end

  def ajax_edit
    recording = Recording.find(params[:id])
    render partial: 'recordings/ajax_edit', locals: {recording: recording}
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(recording_params)
    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render :show, status: :created, location: @recording }
      else
        format.html { render :new }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1
  # PATCH/PUT /recordings/1.json
  def update
    if User.belongs_to_unit?(@recording.unit)
      respond_to do |format|
        if @recording.update(recording_params)
          @avalon_item = @recording.avalon_item
          format.html { render partial: 'recordings/ajax_show', locals: {recording: @recording}, status: :ok, location: @recording }
        else
          format.json { render json: @recording.errors, status: :unprocessable_entity }
        end
      end
    else
      render 'recordings/not_authorized'
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    if User.belongs_to_unit? @recording.unit
      @recording.destroy
      respond_to do |format|
        format.html { redirect_to recordings_url, notice: 'Recording was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render 'recordings/not_authorized'
    end
  end

  # def mark_needs_review
  #   @recording.needs_review = true
  #   @recording.save!
  #   redirect_to recording_path(@recording)
  # end

  # def mark_reviewed
  #   @recording.needs_review = false
  #   @recording.save!
  #   redirect_to recording_path(@recording)
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.includes(recording_contributor_people: [:person]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recording_params
      params.require(:recording).permit(
          :access_determination, :title, :description, :format, :published, :date_of_first_publication, :date_of_first_publication_text,
          :creation_date, :creation_date_text, :creation_end_date, :country_of_first_publication, :in_copyright, :commercial,
          :copyright_end_date, :copyright_end_date_text, :receipt_of_will_before_90_days_of_death,
          :authority_source, :authority_source_url,
          recording_notes_attributes: [:id, :creator, :text, :_destroy]
      )
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_ajax_edit.html.erb
<div data-recording-id="<%= recording.id %>" class="recording_div">
  <h3 class="accordion accordion-title active"><%= recording.title %> <%= recording.mdpi_barcode %></h3>
  <%= nested_form_for recording, remote: true do |f|%>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="rvt-grid">
      <div class="rvt-grid__item-12">
        <label for="recordingTitle">Title</label>
        <%= f.text_field :title, {type: "text", 'aria-describedby': "title"} %>
      </div>
      <div class="rvt-grid__item-12">
        <label for="recordingDescription">Recording Description</label>
        <%= f.text_area :description, {class: "noBorder"} %>
      </div>
      <div class="rvt-grid__item-4-md-up rvt-checkbox-wrapper">
        <label for="recording[in_copyright]" class="rvt-m-right-sm">In Copyright</label>
        <%= f.select :in_copyright, options_for_select([['Yes', true],['No', false]], recording.in_copyright), {include_blank: ''} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="copyrightEnd">Copyright End Date</label>
        <%= f.text_field :copyright_end_date_text, {type:"text", 'aria-describedby':"copyrightEnd", class: 'edtf', placeholder: 'YYYY/MM/DD (EDTF)'} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="recording[commercial]">Commercial</label> <br>
        <%= f.select :commercial, options_for_select([['Yes', true],['No', false]], recording.commercial), {include_blank: ''} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="published">Published</label>
        <%= f.select :published, options_for_select([['Yes', true],['No', false]], recording.published), {include_blank: ''} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="dateOfFirstPublication">Date Of First Publication</label>
        <%= f.text_field :date_of_first_publication_text, {type: "text", 'aria-describedby': "dateOfFirstPublication",  placeholder: 'YYYY/MM/DD (EDTF)', class: 'edtf'} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="creationDate">Creation Date</label>
        <%= f.text_field :creation_date_text, {type: "text", 'aria-describedby': "creationDate",  placeholder: 'YYYY/MM/DD (EDTF)', class: 'edtf'} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="countryOfFirstPublication">Country Of First Publication</label>
        <%= f.text_field :country_of_first_publication, {type: "text", 'aria-describedby': "creationDate", class: 'edtf'} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="authoritySource">Authority Source</label>
        <%= f.text_field :authority_source, {type: "text", 'aria-describedby': "creationDate"} %>
      </div>
      <div class="rvt-grid__item-12">
        <label for="authoritySourceURL">Authority Source URL</label>
        <%= f.text_field :authority_source_url, {type: "url", 'aria-describedby': "creationDate"} %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <% if recording.avalon_item.pod_unit == 'B-ATM' %>
          <label for="receiptOfWill">Receipt Of Will Before 90 Days Of Death</label>
          <%= f.text_field :receipt_of_will_before_90_days_of_death, {type: "text", 'aria-describedby': "receiptOfWill"} %>
        <% end %>
      </div>
      <div class="rvt-grid__item-12">
        <label for="notes">Recording Notes</label>
        <div class="rvt-grid__item-12">
          <%= f.fields_for :recording_notes do |ff| %>
            <%= ff.hidden_field :creator, value: User.current_username %>
            <label for="">Recording Note</label>
            <%= ff.text_area :text, {class: "swal2-textarea", 'aria-labelledby': "notes"}%>
            <%= ff.link_to_remove "Delete", class: 'rvt-button'%>
          <% end %>
          <%= f.link_to_add "Add Note", :recording_notes, class: 'rvt-button rvt-m-top-sm' %>
        </div>
        <button type="button" class="recordingEditCancelButton rvt-button floatRight rvt-m-left-sm" data-recording-id="<%= recording.id %>">Cancel</button>
        <button type="submit" class="recordingEditUpdateButton rvt-button floatRight" data-recording-id="<%= recording.id %>">Save</button>
      </div>
  </div>
  <% end %>
</div>

app/views/recordings/_ajax_show.html.erb
<div data-recording-id="<%= recording.id %>" class="recording_div" >
  <h3 class="accordion accordion-title active accordion-trigger" aria-expanded="true"><%= recording.title %> <%= recording.mdpi_barcode %> <span class="accordion-icon"></span></h3>
  <div>
    <div class="rvt-grid m-fadeIn">
      <div class="rvt-grid__item-12">
        <h3>Recording Description</h3>
        <p><%= recording.description %></p>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="inCopyright">In Copyright</label> <br>
        <%= recording.in_copyright %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="copyrightEnd">Copyright End Date</label> <br>
        <%= recording.copyright_end_date_text %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="commercial">Commercial</label> <br>
        <%= boolean_to_yes_no recording.commercial %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="published">Published</label>
        <br><%= boolean_to_yes_no recording.published %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="dateOfFirstPublication">Date Of First Publication</label>
        <br><%= recording.date_of_first_publication_text %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="creationDate">Creation Date</label>
        <br><%= recording.creation_date_text %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="countryOfFirstPublication">Country Of First Publication</label>
        <br><%= recording.country_of_first_publication %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <label for="authoritySource">Authority Source</label>
        <br><%= recording.authority_source %>
      </div>
      <div class="rvt-grid__item-12">
        <label for="authoritySourceURL">Authority Source URL</label>
        <br><%= recording.authority_source_url %>
      </div>
      <div class="rvt-grid__item-4-md-up">
        <% if @avalon_item.pod_unit == 'B-ATM' %>
          <label for="receiptOfWill">Receipt Of Will Before 90 Days Of Death</label><br>
          <%= recording.receipt_of_will_before_90_days_of_death %>
        <% end %>
      </div>
      <div class="rvt-grid__item-12 rvt-m-top-xs">
        <h4>Recording Notes</h4>
        <div class="rvt-grid">
          <% recording.recording_notes.each do |note| %>
            <div class="bgWhite rvt-p-all-xxs rvt-grid__item-4-md-up rvt-m-right-xxs note">
              <label class="rvt-m-bottom-none">Creator:&nbsp;</label><%= note.creator %> <label class="rvt-m-bottom-none">Date: </label> <%= note.created_at.strftime("%d/%m/%Y") %>
              <p class="rvt-m-top-none"><%= simple_format(note.text) %></p>
            </div>
          <% end %>
        </div>
      </div>
      <% if recording.people.size > 0 %>
        <div class="rvt-grid__item-12 rvt-m-top-xs">
          <h4>Contributors</h4>
          <div class="rvt-grid">
            <% recording.people.each_with_index do |p, i| %>
              <% @person = p %>
              <div class="rvt-grid__item-4-md-up rvt-m-right-xxs rvt-p-all-xs tooltip person">
                <%= link_to (p.entity? ? p.company_name : p.full_name), ajax_edit_person_path(p.id), class: 'red_700', remote: true %>
                <span class="tooltiptext <%= i % 3 == 0 ? 'left_one' : i % 3 == 1 ? 'middle_one' : 'right_one' %>">
                    <%= render partial: 'people/ajax_show', locals: {recording: recording, track: nil} %>
                  </span>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="rvt-grid__item-12">
        <button class="rvt-button floatRight editRecordingButton" data-recording-id="<%= recording.id %>">Edit Recording</button>
      </div>
    </div>

    <div class="performances rvt-p-left-lg" data-recording-id="<%= recording.id %>">
      <h2>Performances <span> <button class="rvt-button rvt-m-left-lg createPerformanceButton" data-recording-id="<%= recording.id %>" >Create New Performance</button></span></h2>
      <% recording.performances.each do |p| %>
        <%= render partial: 'performances/ajax_show', locals: {performance: p} %>
      <% end %>
    </div>
  </div>
</div>

app/views/recordings/_form.html.erb
<%= form_for @recording do |f| %>
  <%= f.hidden_field :last_updated_by, value: User.current_username %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="">
  <table>
    <tbody>
    <tr>
      <th>Title</th>
      <td>
        <%= f.text_field :title %>
      </td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= f.text_area :description %></td>
    </tr>
    <tr>
      <th>Format</th>
      <td><%= f.text_field :format %></td>
    </tr>
    <tr>
      <th>MDPI Barcode</th>
      <td>
        <%= @recording.mdpi_barcode %>
      </td>
    </tr>
    <tr>
      <th>Published?</th>
      <td><%= f.select :published, [['', nil], ['Yes', true], ['No', false]]%></td>
    </tr>
    <tr>
      <th>Date of First Publication</th>
      <td><%= f.text_field :date_of_first_publication, {class: 'edtf', placeholder: 'YYYY/MM/DD (EDTF)'} %><span class="ui-icon ui-icon-help"></span></td>
    </tr>
    <tr>
      <th>Creation Date</th>
      <td><%= f.text_field :creation_date, {class: 'edtf', placeholder: 'YYYY/MM/DD (EDTF)'} %><span class="ui-icon ui-icon-help"></span></td>
    </tr>
    <tr>
      <th>Creation End Date</th>
      <td><%= f.text_field :creation_end_date, {class: 'edtf', placeholder: 'YYYY/MM/DD (EDTF)'}%><span class="ui-icon ui-icon-help"></span></td>
    </tr>
    <tr>
      <th>Country of First Publication</th>
      <td><%= f.text_field :country_of_first_publication %></td>
    </tr>
    <tr>
      <th>Producer</th>
      <td>blank for now until we can associate contributors</td>
    </tr>
    <tr>
      <th>In Copyright?</th>
      <td><%= f.select :in_copyright, [['', nil], ['Yes', true], ['No', false]] %></td>
    </tr>
    <tr>
      <th>Copyright End Date</th>
      <td><%= f.text_field :copyright_end_date, {class: 'edtf', placeholder: 'YYYY/MM/DD (EDTF)'} %></td>
    </tr>
    <% if @recording.avalon_item == 'B-ATM' %>
      <tr>
        <th>Receipt Of Will Before 90 Days Of Death?</th>
        <td><%= f.select :receipt_of_will_before_90_days_of_death, [['', nil], ['Yes', true], ['No', false]] %></td>
      </tr>
    <% end %>
    <tr>
      <th>Authority Source</th>
      <td><%= f.text_field :authority_source %></td>
    </tr>
    <tr>
      <th>Authority Source URL</th>
      <td><%= f.text_field :authority_source_url, class: 'urlValidator' %></td>
    </tr>
    <tr>
      <th>Notes</th>
      <td>Repeatable notes once we can create them</td>
    </tr>
    <tr>
      <th>Access Determination</th>
      <td>
        <%= f.select :access_determination, options_for_select(AccessDeterminationHelper::ACCESS_DECISIONS, @recording.access_determination) %>
      </td>
    </tr>
    <tr class="submit_row">
      <td></td>
      <td><%= f.submit %></td>
    </tr>
    </tbody>
  </table>
</div>
<% end %>

app/views/recordings/not_authorized.html.erb
<div>
  <p class="warning">The record you are trying to access belongs to a Unit that you are not a member of.</p>
  <p>Trying to access: <%= @recording.unit %></p>
  <p>You belong to: <%= UnitsHelper.human_readable_units %></p>
</div>