config/routes.rb
Rails.application.routes.draw do
  resources :avalon_items
  resources :avalon_item_notes, only: [:new, :create]
  resources :people
  resources :performances
  resources :performance_notes, only: [:new, :create]
  resources :policies
  resources :recording_contributors
  resources :recording_notes, only: [:new, :create]
  resources :recordings
  resources :tracks
  resources :contracts

  get '/nav/search', to: 'nav#search', as: "search"
  get '/date_search', to: 'nav#date_search_get', as: 'date_search_get'
  post '/date_search', to: 'nav#date_search_post', as: 'date_search_post'

  get '/nav/test', to: 'nav#test', as: 'nav_test'
  get '/user_guide', to: 'nav#user_guide', as: 'user_guide'
  get '/atom_tester/search', to: 'atom_feed_reader#search', as: 'atom_feed_search'

  get '/atom_tester', to: 'atom_feed_reader#index', as: 'atom_feed_tester'
  get '/atom_tester/json/:id', to: 'atom_feed_reader#read_json', as: 'atom_feed_read_json'
  get '/atom_tester/load_avalon_record/:id', to: 'atom_feed_reader#load_avalon_record', as: 'load_avalon_record'

  get '/people/new/entity/', to: 'people#new_entity', as: 'new_entity'

  get '/services/access_decisions_tester', to: 'test#test_access_decisions', as: 'test_access_decisions'
  get '/services/access_determination/:avalon_identifier', to: 'services#access_determination', as: 'access_determination'

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signoutg', to: 'sessions#destroy', via: :get

  resources :sessions, only: [:new, :destroy] do
    get :validate_login, on: :collection
  end

  get '/users/', to: 'user#index', as: 'users'
  get '/user/ldap_lookup', to: 'user#ldap_lookup', as: 'ldap_lookup'

  resources :works

  post '/avalon_items/access_decision', to: 'avalon_items#ajax_post_access_decision', as: 'ajax_avalon_item_access_decision'
  post '/avalon_items/ajax_needs_review', to: 'avalon_items#ajax_post_needs_review', as: 'ajax_post_needs_review'
  post '/avalon_items/ajax_reviewed', to: 'avalon_items#ajax_post_reviewed', as: 'ajax_post_reviewed'
  get '/avalon_items/ajax/calced_access_determination/:id', to: 'avalon_items#ajax_calced_access', as: 'ajax_avalon_item_calced_access'
  get '/avalon_items/cm/cm_all', to: 'avalon_items#cm_all_items', as: 'avalon_all_cm_items'
  get '/avalon_items/cm/cm_iu_default_only', to: 'avalon_items#cm_iu_default_only', as: 'avalon_items_cm_iu_default_only'
  get '/avalon_items/cm/cm_waiting_on_cl', to: 'avalon_items#cm_waiting_on_cl', as: 'avalon_items_cm_waiting_on_cl'
  get '/avalon_items/cm/cm_waiting_on_self', to: 'avalon_items#cm_waiting_on_self', as: 'avalon_items_cm_waiting_on_self'
  get '/avalon_items/cm/cm_access_determined', to: 'avalon_items#cm_access_determined', as: 'avalon_items_cm_access_determined'
  get '/avalon_items/cm/cm_published', to: 'avalon_items#cm_published', as: 'avalon_items_cm_published'

  get '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder', as: 'ajax_people_adder_get'
  post '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder_post', as: 'ajax_people_adder_post'
  get '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter', as: 'ajax_people_setter_get'
  post '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter_post', as: 'ajax_people_setter_post'
  get '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter', as: 'ajax_work_setter_get'
  post '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter_post', as: 'ajax_work_setter_post'
  get '/ajax/people/ajax_work_person_form', to: "people#ajax_work_person_form", as: 'ajax_work_person_form'

  get '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder', as: 'ajax_work_adder_get'
  post '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder_post', as: 'ajax_work_adder_post'
  post 'avalon_items/:id/ajax_add_note', to: 'avalon_items#ajax_add_note', as: 'ajax_avalon_item_add_note'

  get '/avalon_items/ajax/cl_all', to: 'avalon_items#ajax_all_cl_items', as: 'ajax_avalon_cl_all'
  get '/avalon_items/ajax/cl_initial_review', to: 'avalon_items#ajax_cl_initial_review', as: 'avalon_items_cl_initial_review'
  get '/avalon_items/ajax/cl_waiting_on_cm', to: 'avalon_items#ajax_cl_waiting_on_cm', as: 'avalon_items_cl_waiting_on_cm'
  get '/avalon_items/ajax/cl_waiting_on_self', to: 'avalon_items#ajax_cl_waiting_on_self', as: 'avalon_items_cl_waiting_on_self'
  get '/avalon_items/ajax/cl_access_determined', to: 'avalon_items#ajax_cl_access_determined', as: 'avalon_items_cl_access_determined'

  get '/collections/', to: "collections#index", as: 'collections_index'
  post '/collections/', to: "collections#assign_access", as: 'collection_assign'
  get '/collection/', to: "collections#collection_list", as: "collection_list"

  get '/contracts/ajax/new/:ai_id', to: 'contracts#ajax_new', as: 'ajax_new_contract'
  post '/contracts/ajax/create', to: 'contracts#ajax_create', as: 'ajax_create_contract'
  get '/contracts/ajax/edit/:id', to: 'contracts#ajax_edit', as: 'ajax_edit_contract'
  post '/contracts/ajax/update', to: 'contracts#ajax_update', as: 'ajax_update_contract'
  get '/contracts/ajax/show/:id', to: 'contracts#ajax_show', as: 'ajax_show_contract'

  get 'recordings/ajax/edit/:id', to: 'recordings#ajax_edit', as: 'ajax_edit_recording'
  get 'recordings/ajax/show/:id', to: 'recordings#ajax_show', as: 'ajax_show_recording'

  get '/people/ajax/new', to: 'people#ajax_new_person', as: 'ajax_new_person'
  get '/people/ajax/autocomplete', to: 'people#ajax_autocomplete', as: 'people_ajax_autocomplete'
  get '/people/ajax/autocomplete_company', to: "people#ajax_autocomplete_company", as: "people_ajax_autocomplete_company"
  get '/people/ajax/edit/:id', to: 'people#ajax_edit_person', as: 'ajax_edit_person'

  get '/performances/ajax/new/:recording_id', to: 'performances#ajax_new_performance', as: 'ajax_new_performance'
  get '/performances/ajax/edit/:id', to: 'performances#ajax_edit_performance', as: 'ajax_edit_performance'
  get '/performances/ajax/show/:id', to: 'performances#ajax_show_performance', as: 'ajax_Show_performance'
  post '/performances/ajax/access_determination', to: 'performances#ajax_access_determination', as: 'ajax_performance_access_determination'

  get '/tracks/ajax/new/:performance_id', to: 'tracks#ajax_new_track', as: 'ajax_new_track'
  get '/tracks/ajax/edit/:track_id', to: 'tracks#ajax_edit_track', as: 'ajax_edit_track'
  post '/tracks/ajax/access_determination', to: 'tracks#ajax_access_determination', as: 'ajax_track_access_determination'

  post '/users/ajax/set_user_unit/:username/:unit/:access', to: 'user#ajax_set_user_unit', as: 'ajax_set_user_unit'
  post '/users/ajax/set_user_cl/:username', to: 'users#ajax_toggle_cl', as: 'ajax_set_user_cl'
  get '/works/ajax/new', to: 'works#ajax_new_work', as: 'ajax_new_work'
  get '/works/ajax/:id', to: 'works#ajax_show', as: 'ajax_show_work'
  get '/work/ajax/autocomplete_title', to: 'works#ajax_autocomplete_title', as: 'work_ajax_autocomplete_title'
  get '/work/ajax/edit/:id', to: 'works#ajax_edit_work', as: 'ajax_edit_work'

  root 'nav#start'

end

app/models/recording.rb
class Recording < ApplicationRecord
  include AccessDeterminationHelper

  has_many :recording_performances, dependent: :destroy
  has_many :recording_notes, dependent: :destroy
  has_many :performances, through: :recording_performances, dependent: :destroy

  # this one is wonky because recording_contributor_people holds the role booleans (producer and depositor). A Person only
  # contributes if a role is set. But the RecordingContributorPerson can exist with any roles being set to true so we have
  # to abstract the actual people through the middle query of :contributors
  has_many :recording_contributor_people
  has_many :contributors, -> { where "recording_producer = true OR recording_depositor = true" }, class_name: "RecordingContributorPerson"
  has_many :people, through: :contributors

  after_destroy :killed


  belongs_to :atom_feed_read
  belongs_to :avalon_item
  has_one :pod_physical_object, class_name: 'PodPhysicalObject', foreign_key: 'mdpi_barcode', primary_key: 'mdpi_barcode'
  has_one :pod_unit, through: :pod_physical_object

  accepts_nested_attributes_for :recording_notes, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :performances

  before_save :edtf_dates

  after_save :update_avalon_items

  UNITS = ["B-AAAI", "B-AAAMC", "B-AFRIST", "B-ALF", "B-ANTH", "B-ARCHIVES", "B-ASTR", "B-ATHBASKM", "B-ATHBASKW",
           "B-ATHFHOCKEY", "B-ATHFTBL", "B-ATHROWING", "B-ATHSOCCM", "B-ATHSOFTB", "B-ATHTENNM", "B-ATHVIDEO",
           "B-ATHVOLLW", "B-ATM", "B-BCC", "B-BFCA", "B-BUSSPEA", "B-CAC", "B-CDEL", "B-CEDIR", "B-CELCAR", "B-CELTIE",
           "B-CEUS", "B-CHEM", "B-CISAB", "B-CLACS", "B-CMCL", "B-CREOLE", "B-CSHM", "B-CYCLOTRN", "B-EASC", "B-EDUC",
           "B-EPPLEY", "B-FACILITY", "B-FINEARTS", "B-FOLKETHNO", "B-FRANKLIN", "B-GBL", "B-GEOLOGY", "B-GLBTSSSL",
           "B-GLEIM", "B-GLOBAL", "B-HPER", "B-IAS", "B-IAUNRC", "B-IPRC", "B-IUAM", "B-IULMIA", "B-JOURSCHL", "B-KINSEY",
           "B-LACASA", "B-LAW", "B-LIBERIA", "B-LIFESCI", "B-LILLY", "B-LING", "B-MATHERS", "B-MDP", "B-MUSBANDS", "B-MUSIC",
           "B-MUSOPERA", "B-MUSREC", "B-OID", "B-OPTMSCHL", "B-OPTOMTRY", "B-POLISH", "B-PSYCH", "B-RECSPORTS", "B-REEI",
           "B-RTVS", "B-SAGE", "B-SAVAIL", "B-SWAIN", "B-TAI", "B-THTR", "B-UNDRWATR", "B-UNIVCOMM", "B-WELLS", "B-WEST",
           "EA-ARCHIVES", "EA-ATHL", "I-ARCHIVES", "I-DENT", "I-LIBR-SCA", "I-RAYBRAD", "KO-ARCHIVES", "NW-ARCHIVES",
           "SB-ARCHIVES", "SB-PHYS", "SB-ULIB", "SE-ARCHIVES"]

  validates :access_determination, :inclusion => {:in => ACCESS_DECISIONS}

  def contributors
    people.map { |p| p.name }
  end

  def edtf_dates
    # copyright end date
    date = Date.edtf(copyright_end_date_text.gsub('/', '-'))
    self.copyright_end_date = date
    puts "Set copyright_end_date to #{date}, calling self.copyright_end_date: #{self.copyright_end_date}"

    # creation date
    date = Date.edtf(creation_date_text.gsub('/', '-'))
    self.creation_date = date
    #puts "Set creation_date to #{date}, calling self.creation_date: #{self.creation_date}"

    # date of first pub
    date = Date.edtf(date_of_first_publication_text.gsub('/', '-'))
    self.date_of_first_publication = date
    #puts "Set date_of_first_publication to #{date}, calling self.date_of_first_publication: #{self.date_of_first_publication}"
  end

  private
  def update_avalon_items
    avalon_item.update(structure_modified: true)
  end

  def killed
    puts "#{self.class}:#{self.id} destroyed!"
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: [:show, :edit, :update, :destroy, :mark_needs_review, :mark_reviewed]


  # GET /recordings
  # GET /recordings.json
  def index
    @avalon_items = AvalonItem.where(pod_unit: UnitsHelper.human_readable_units_search(User.current_username)).order(:title)
  end

  # GET /recordings/1
  # GET /recordings/1.json
  # def show
  #   if User.belongs_to_unit?(@recording.unit)
  #     render :show
  #   else
  #     render 'recordings/not_authorized'
  #   end
  # end

  def ajax_show
    recording = Recording.find(params[:id])
    @avalon_item = recording.avalon_item
    render partial: 'recordings/ajax_show', locals: {recording: recording}
  end

  # GET /recordings/new
  def new
    @recording = Recording.new
  end

  # GET /recordings/1/edit
  def edit
    render 'recordings/not_authorized' unless User.belongs_to_unit?(@recording.unit)
  end

  def ajax_edit
    recording = Recording.find(params[:id])
    render partial: 'recordings/ajax_edit', locals: {recording: recording}
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(recording_params)
    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render :show, status: :created, location: @recording }
      else
        format.html { render :new }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1
  # PATCH/PUT /recordings/1.json
  def update
    if User.belongs_to_unit?(@recording.unit)
      respond_to do |format|
        if @recording.update(recording_params)
          @avalon_item = @recording.avalon_item
          format.html { render partial: 'recordings/ajax_show', locals: {recording: @recording}, status: :ok, location: @recording }
        else
          format.json { render json: @recording.errors, status: :unprocessable_entity }
        end
      end
    else
      render 'recordings/not_authorized'
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    if User.belongs_to_unit? @recording.unit
      @recording.destroy
      respond_to do |format|
        format.html { redirect_to recordings_url, notice: 'Recording was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render 'recordings/not_authorized'
    end
  end

  # def mark_needs_review
  #   @recording.needs_review = true
  #   @recording.save!
  #   redirect_to recording_path(@recording)
  # end

  # def mark_reviewed
  #   @recording.needs_review = false
  #   @recording.save!
  #   redirect_to recording_path(@recording)
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.includes(recording_contributor_people: [:person]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recording_params
      params.require(:recording).permit(
          :access_determination, :title, :description, :format, :published, :date_of_first_publication, :date_of_first_publication_text,
          :creation_date, :creation_date_text, :creation_end_date, :country_of_first_publication, :in_copyright, :commercial,
          :copyright_end_date, :copyright_end_date_text, :receipt_of_will_before_90_days_of_death,
          :authority_source, :authority_source_url,
          recording_notes_attributes: [:id, :creator, :text, :_destroy]
      )
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/old_/edit.html.erb
<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>
<h1>Editing Recording</h1>
<%= render 'form' %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
      $('form.edit_recording').submit(function(event) {
          if (valid()) {
              return true
          } else {
              event.preventDefault();
              swal.fire({
                  title: "Cannot Update Recording",
                  type: 'error',
                  html: invalidMessage(),
                  showCloseButton: true,
                  showCancelButton: false,
                  confirmButtonText: "Ok"
              })
          }
      });
      hookEdtfValidation();
      hookYearValidation();
      hookUrlValidator();
  });

  function valid() {
      return $('.badEdtf').size() === 0 && $('.badYear').size() === 0 && $('.badUrl').size() === 0
  }

  function invalidMessage() {
      let msg = "<ul style=\"list-style-type: none\">";
      if ($('.badEdtf').size() > 0) {
          msg += "<li>One or more of your dates is not EDTF compliant</li>";
      }
      if ($('.badYear').size() > 0) {
          msg += "<li><i>Enters Public Domain</i> is not a valid Year (<b>YYYY</b>)</li>";
      }
      if ($('.badUrl').size() > 0) {
          msg += "<li>Your <i>Authority Source</i> is not a valid URL</li>";
      }
      return msg;
  }

</script>

app/views/recordings/old_/new.html.erb
<h1>New Recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/old_/show.html.erb
<p id="notice"><%= notice %></p>
<div style="margin-bottom: 15px">
  <%= link_to 'Edit', edit_recording_path(@recording) %> |
  <%= link_to "Avalon Item: #{@recording.avalon_item.title}", url_for(@recording.avalon_item) %>
</div>
<div class="left w_400">
<h4>Recording</h4>
  <table id="recording_table">
    <tbody>
    <tr>
      <th>Title</th>
      <td>
        <%= @recording.title %>
      </td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @recording.description %></td>
    </tr>
    <tr>
      <th>Format</th>
      <td><%= @recording.format %></td>
    </tr>
    <tr>
      <th>MDPI Barcode</th>
      <td>
        <%= @recording.mdpi_barcode %>
      </td>
    </tr>
    <tr>
      <th>Published?</th>
      <td><%= @recording.published? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Date Of First Publication</th>
      <td><%= @recording.date_of_first_publication %></td>
    </tr>
    <tr>
      <th>Creation Date</th>
      <td><%= @recording.creation_date %></td>
    </tr>
    <tr>
      <th>Creation End Date</th>
      <td><%= @recording.creation_end_date %></td>
    </tr>
    <tr>
      <th>Country Of First Publication</th>
      <td><%= @recording.country_of_first_publication %></td>
    </tr>
    <tr>
      <th>Producers (once we have contributors set up)'</th>
      <td></td>
    </tr>
    <tr>
      <th>In Copyright?</th>
      <td><%= @recording.in_copyright %></td>
    </tr>
    <tr>
      <th>Copyright End Date</th>
      <td><%= @recording.copyright_end_date %></td>
    </tr>
    <% if @recording.avalon_item.pod_unit == 'B-ATM' %>
      <tr>
        <th>Receipt Of Will Before 90 Days Of Death?</th>
        <td><%= @recording.receipt_of_will_before_90_days_of_death? ? 'Yes' : 'No' %></td>
      </tr>
    <% end %>
    <tr>
      <th>Authority Source</th>
      <td><%= link_to @recording.authority_source, @recording.authority_source, {target: '_blank'} unless @recording.authority_source.blank? %></td>
    </tr>
    <tr>
      <th>Access Determination</th>
      <td><%= @recording.access_determination %></td>
    </tr>
    <tr>
      <th>Notes when we have them</th>
      <td></td>
    </tr>
    </tbody>
  </table>
</div>
<div class="left">
  <%# if @recording.needs_review? %>
  <%#= button_to "Reviewed", mark_reviewed_recording_path(@recording), method: 'post' %>
  <%# else %>
  <%#= button_to "Needs Review", mark_needs_review_recording_path(@recording), method: 'post' %>
  <%# end %>
  <% if !@recording.catalog_key.nil? %>
    <div class="iucat_link_div">
      <a href="https://iucat.iu.edu/catalog/<%= @recording.catalog_key %>" target="_blank">IUCAT Record</a>
    </div>
  <% end %>
  <% if @recording.fedora_item_id.blank? %>
    <div class="iucat_link_div">
      <a href="#">No Fedora ID in the database...</a>
    </div>
  <% else %>
    <%= link_to "MCO Item", "#" %>
  <% end %>
</div>

<div class="clear m_top_10">

</div>
<h4>Performances On This Recording...</h4>
<table>
  <tbody>
  <% @recording.performances.each do |p| %>
  <dir>
    <b>Location:</b>&nbsp;<%= p.location %> <br>
    <b>Performance Date: </b><%= p.performance_date %>
  </dir>
  <% end %>
  </tbody>
</table>
<br><br><br><br>