config/routes.rb
Rails.application.routes.draw do
  resources :avalon_items
  resources :avalon_item_notes, only: [:new, :create]
  resources :people
  resources :performances
  resources :performance_notes, only: [:new, :create]
  resources :policies
  resources :recording_contributors
  resources :recording_notes, only: [:new, :create]
  resources :recordings
  resources :tracks
  resources :contracts

  get '/nav/search', to: 'nav#search', as: "search"
  get '/date_search', to: 'nav#date_search_get', as: 'date_search_get'
  post '/date_search', to: 'nav#date_search_post', as: 'date_search_post'

  get '/nav/test', to: 'nav#test', as: 'nav_test'
  get '/user_guide', to: 'nav#user_guide', as: 'user_guide'
  get '/atom_tester/search', to: 'atom_feed_reader#search', as: 'atom_feed_search'

  get '/atom_tester', to: 'atom_feed_reader#index', as: 'atom_feed_tester'
  get '/atom_tester/json/:id', to: 'atom_feed_reader#read_json', as: 'atom_feed_read_json'
  get '/atom_tester/load_avalon_record/:id', to: 'atom_feed_reader#load_avalon_record', as: 'load_avalon_record'

  get '/people/new/entity/', to: 'people#new_entity', as: 'new_entity'

  get '/services/access_decisions_tester', to: 'test#test_access_decisions', as: 'test_access_decisions'
  get '/services/access_determination/:avalon_identifier', to: 'services#access_determination', as: 'access_determination'

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signoutg', to: 'sessions#destroy', via: :get

  resources :sessions, only: [:new, :destroy] do
    get :validate_login, on: :collection
  end

  get '/users/', to: 'user#index', as: 'users'
  get '/user/ldap_lookup', to: 'user#ldap_lookup', as: 'ldap_lookup'

  resources :works

  post '/avalon_items/access_decision', to: 'avalon_items#ajax_post_access_decision', as: 'ajax_avalon_item_access_decision'
  post '/avalon_items/ajax_needs_review', to: 'avalon_items#ajax_post_needs_review', as: 'ajax_post_needs_review'
  post '/avalon_items/ajax_reviewed', to: 'avalon_items#ajax_post_reviewed', as: 'ajax_post_reviewed'
  get '/avalon_items/ajax/calced_access_determination/:id', to: 'avalon_items#ajax_calced_access', as: 'ajax_avalon_item_calced_access'
  get '/avalon_items/cm/cm_all', to: 'avalon_items#cm_all_items', as: 'avalon_all_cm_items'
  get '/avalon_items/cm/cm_iu_default_only', to: 'avalon_items#cm_iu_default_only', as: 'avalon_items_cm_iu_default_only'
  get '/avalon_items/cm/cm_waiting_on_cl', to: 'avalon_items#cm_waiting_on_cl', as: 'avalon_items_cm_waiting_on_cl'
  get '/avalon_items/cm/cm_waiting_on_self', to: 'avalon_items#cm_waiting_on_self', as: 'avalon_items_cm_waiting_on_self'
  get '/avalon_items/cm/cm_access_determined', to: 'avalon_items#cm_access_determined', as: 'avalon_items_cm_access_determined'
  get '/avalon_items/cm/cm_published', to: 'avalon_items#cm_published', as: 'avalon_items_cm_published'

  get '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder', as: 'ajax_people_adder_get'
  post '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder_post', as: 'ajax_people_adder_post'
  get '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter', as: 'ajax_people_setter_get'
  post '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter_post', as: 'ajax_people_setter_post'
  get '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter', as: 'ajax_work_setter_get'
  post '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter_post', as: 'ajax_work_setter_post'
  get '/ajax/people/ajax_work_person_form', to: "people#ajax_work_person_form", as: 'ajax_work_person_form'

  get '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder', as: 'ajax_work_adder_get'
  post '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder_post', as: 'ajax_work_adder_post'
  post 'avalon_items/:id/ajax_add_note', to: 'avalon_items#ajax_add_note', as: 'ajax_avalon_item_add_note'

  get '/avalon_items/ajax/cl_all', to: 'avalon_items#ajax_all_cl_items', as: 'ajax_avalon_cl_all'
  get '/avalon_items/ajax/cl_initial_review', to: 'avalon_items#ajax_cl_initial_review', as: 'avalon_items_cl_initial_review'
  get '/avalon_items/ajax/cl_waiting_on_cm', to: 'avalon_items#ajax_cl_waiting_on_cm', as: 'avalon_items_cl_waiting_on_cm'
  get '/avalon_items/ajax/cl_waiting_on_self', to: 'avalon_items#ajax_cl_waiting_on_self', as: 'avalon_items_cl_waiting_on_self'
  get '/avalon_items/ajax/cl_access_determined', to: 'avalon_items#ajax_cl_access_determined', as: 'avalon_items_cl_access_determined'

  get '/collections/', to: "collections#index", as: 'collections_index'
  post '/collections/', to: "collections#assign_access", as: 'collection_assign'
  get '/collection/', to: "collections#collection_list", as: "collection_list"

  get '/contracts/ajax/new/:ai_id', to: 'contracts#ajax_new', as: 'ajax_new_contract'
  post '/contracts/ajax/create', to: 'contracts#ajax_create', as: 'ajax_create_contract'
  get '/contracts/ajax/edit/:id', to: 'contracts#ajax_edit', as: 'ajax_edit_contract'
  post '/contracts/ajax/update', to: 'contracts#ajax_update', as: 'ajax_update_contract'
  get '/contracts/ajax/show/:id', to: 'contracts#ajax_show', as: 'ajax_show_contract'

  get 'recordings/ajax/edit/:id', to: 'recordings#ajax_edit', as: 'ajax_edit_recording'
  get 'recordings/ajax/show/:id', to: 'recordings#ajax_show', as: 'ajax_show_recording'

  get '/people/ajax/new', to: 'people#ajax_new_person', as: 'ajax_new_person'
  get '/people/ajax/autocomplete', to: 'people#ajax_autocomplete', as: 'people_ajax_autocomplete'
  get '/people/ajax/autocomplete_company', to: "people#ajax_autocomplete_company", as: "people_ajax_autocomplete_company"
  get '/people/ajax/edit/:id', to: 'people#ajax_edit_person', as: 'ajax_edit_person'

  get '/performances/ajax/new/:recording_id', to: 'performances#ajax_new_performance', as: 'ajax_new_performance'
  get '/performances/ajax/edit/:id', to: 'performances#ajax_edit_performance', as: 'ajax_edit_performance'
  get '/performances/ajax/show/:id', to: 'performances#ajax_show_performance', as: 'ajax_Show_performance'
  post '/performances/ajax/access_determination', to: 'performances#ajax_access_determination', as: 'ajax_performance_access_determination'

  get '/tracks/ajax/new/:performance_id', to: 'tracks#ajax_new_track', as: 'ajax_new_track'
  get '/tracks/ajax/edit/:track_id', to: 'tracks#ajax_edit_track', as: 'ajax_edit_track'
  post '/tracks/ajax/access_determination', to: 'tracks#ajax_access_determination', as: 'ajax_track_access_determination'

  post '/users/ajax/set_user_unit/:username/:unit/:access', to: 'user#ajax_set_user_unit', as: 'ajax_set_user_unit'
  post '/users/ajax/set_user_cl/:username', to: 'users#ajax_toggle_cl', as: 'ajax_set_user_cl'
  get '/works/ajax/new', to: 'works#ajax_new_work', as: 'ajax_new_work'
  get '/works/ajax/:id', to: 'works#ajax_show', as: 'ajax_show_work'
  get '/work/ajax/autocomplete_title', to: 'works#ajax_autocomplete_title', as: 'work_ajax_autocomplete_title'
  get '/work/ajax/edit/:id', to: 'works#ajax_edit_work', as: 'ajax_edit_work'

  root 'nav#start'

end

app/controllers/nav_controller.rb
class NavController < ApplicationController
  include RecordingsHelper
  include AvalonItemsHelper
  include Pagy::Backend

  def start
    if User.current_user_copyright_librarian?
      @pagy, @avalon_items = pagy(AvalonItem.cl_all)
    else
      @pagy, @avalon_items = pagy(AvalonItem.cm_all)
    end
  end

  def test

  end

  def avalon_identifier_search

  end

  def date_search_get
    render 'nav/date_search'
  end

  def date_search_post
    if params[:start_year].blank?
      flash[:warning] = "You must specify at least a start year"
      render 'nav/date_search'
    else
      start_date = Date.new(params[:start_year]&.to_i)
      # the year defaults to jan 1, YYYY but for end year the date needs to be Dec 31, YYYY
      end_date = params[:end_year].blank? ? Date.today : Date.new(params[:end_year].to_i + 1) - 1.day
      @avalon_items = AvalonItem.joins(:recordings).where("recordings.date_of_first_publication >= ? and recordings.date_of_first_publication <= ?", start_date, end_date)
      @works = Work.where("publication_date >= ? AND publication_date <= ?", start_date, end_date)
      render 'nav/date_search'
    end
  end

  def search
    #@avalon_items = AvalonItem.where(:pod_unit => UnitsHelper.human_readable_units_search(User.current_username)).where('title like ?', "%#{params[:search]}%")
    @avalon_items = AvalonItem.solr_search_ads(params[:search])
    @people = Person.solr_search(params[:search])
    @works = Work.solr_search(params[:search])
  end

  def user_guide
    render 'user_guide'
  end

  # Search is no longer based on MDPI barcodes, eventually it will entail fedora ids and free text
  # def mdpi_barcode_search
  #   @recording = Recording.where(mdpi_barcode: params[:mdpi_barcode]).first
  #   if @recording.nil?
  #     @atom_feed_read = AtomFeedReaderHelper.read_atom_record(params[:mdpi_barcode])
  #     # make sure to modify the existing AtomFeedRead object
  #     if @atom_feed_read
  #       @existing = AtomFeedRead.where(avalon_id: @atom_feed_read.avalon_id).first
  #       @atom_feed_read = @existing if @existing
  #     end
  #     json_text = AtomFeedReaderHelper.read_avalon_json(@atom_feed_read.json_url) unless @atom_feed_read.nil?
  #     avalon_item = save_json(json_text) unless @atom_feed_read.nil?
  #     if avalon_item.nil?
  #       flash[:warning] = "Could not find any Recordings in MCO with MDPI barcode: #{params[:mdpi_barcode]}"
  #       redirect_to recordings_path
  #     else
  #       flash[:notice] = "New record(s) were loaded into RMD" unless avalon_item.nil?
  #       redirect_to avalon_item_path(avalon_item) unless avalon_item.nil?
  #     end
  #   else
  #     redirect_to avalon_item_path(@recording.avalon_item)
  #   end
  # end

end

app/views/nav/_cl_avalon_items_table.html.erb
<table id="avalon_items_table" class="rvt-table-compact rvt-table-cells">
  <thead>
    <tr>
      <th class="no_sort"></th>
      <th class="no_sort">Title</th>
      <th class="no_sort">Last Review Comment</th>
      <th>Comment Date</th>
    </tr>
  </thead>
  <tbody>
  <% @avalon_items.each_with_index do |avalon_item, i| %>
    <tr>
      <td>
        <% if avalon_item.review_requested? %>
          <% if avalon_item.any_determinations? %>
            <span class="rvt-badge rvt-badge--info pointer">Re-Review</span>
          <% else %>
            <span class="rvt-badge rvt-badge--info pointer">Initial Review</span>
          <% end %>
        <% elsif avalon_item.waiting_on_cm? %>
          <span class="rvt-badge rvt-badge--warning">Needs Information</span>
        <% elsif avalon_item.waiting_on_cl? %>
          <span class="rvt-badge rvt-badge--danger">Responses</span>
        <% elsif avalon_item.access_determined? %>
          <span class="rvt-badge rvt-badge--success">Access Determined</span>
        <% else %>
          <i>missing badge?</i>
        <% end %>
      </td>
      <td><%= link_to "#{avalon_item.title.blank? ? "No Title!" : avalon_item.title.truncate(35)}", avalon_item_path(avalon_item), class: (avalon_item.title.blank? ? 'blank_title' : '') %></td>
      <td><%= avalon_item.review_comments.size > 0 ? "<i>#{avalon_item.review_comments.last.creator}</i>: #{avalon_item.review_comments.last.comment}".html_safe : '' %></td>
      <td><%= avalon_item.review_comments.size > 0 ? avalon_item.review_comments.last.created_at.strftime("%m/%d/%Y") : '' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/nav/_cl_start.html.erb
<p>Copyright Librarian Workflow</p>
<div class="rvt-m-all-xxs rvt-border-radius">
  <span id="cl_all_badge" class="filter-badge rvt-badge pointer" onclick="clLoadAll()">All</span>
  <span id="cl_initial_badge" class="filter-badge rvt-badge rvt-badge--info-secondary pointer" onclick="clLoadInitial()">Initial Review</span>
  <span id="cl_waiting_on_cm_badge" class="filter-badge rvt-badge rvt-badge--warning-secondary pointer" onclick="clLoadWaitingOnCM()">Needs Information</span>
  <span id="cl_waiting_on_self_badge" class="filter-badge rvt-badge rvt-badge--danger-secondary pointer" onclick="clLoadWaitingOnSelf()">Responses</span>
  <span id="cl_determined_badge" class="filter-badge rvt-badge rvt-badge--success-secondary pointer" onclick="clLoadAccessDetermined()">Access Determined</span>
</div>
<div id="results_table_div">
  <%== pagy_nav(@pagy) %>
  <%= render partial: 'cl_avalon_items_table' %>
</div>

app/views/nav/_cm_avalon_items_table.html.erb
<%== pagy_nav(@pagy) %>
<table id="avalon_items_table" class="rvt-table-compact rvt-table-cells">
  <thead>
    <tr>
      <th class="no_sort"></th>
      <th class="no_sort">Title</th>
      <th>Unit</th>
      <th class="no_sort">Last Review Comment</th>
      <th>Comment Date</th>
    </tr>
  </thead>
  <tbody>
  <% @avalon_items.each_with_index do |avalon_item, i| %>
    <tr>
      <td>
        <% if avalon_item.default_access? %>
          <span class="rvt-badge rvt-badge--info">Default Access</span>
        <% elsif avalon_item.review_requested? %>
          <span class="rvt-badge rvt-badge--warning">Review Requested</span>
        <% elsif avalon_item.waiting_on_cl? %>
          <span class="rvt-badge rvt-badge--warning">Review Requested</span>
        <% elsif avalon_item.waiting_on_cm? %>
          <span class="rvt-badge rvt-badge--danger">Responses</span>
        <% elsif avalon_item.access_determined? and !avalon_item.published_in_mco? %>
          <span class="rvt-badge rvt-badge--success">Access Determined</span>
        <% elsif avalon_item.published_in_mco? %>
          <span class="rvt-badge rvt-badge--info">Published in MCO</span>
        <% else %>
          <i>missing badge?</i>
        <% end %>
      </td>
      <td><%= link_to "#{avalon_item.title.blank? ? "No Title!" : avalon_item.title.truncate(35)}", avalon_item_path(avalon_item), class: (avalon_item.title.blank? ? 'blank_title' : '') %></td>
      <td>
        <%= avalon_item.pod_unit %>
      </td>
      <td><%= avalon_item.review_comments.size > 0 ? "<i>#{avalon_item.review_comments.last.creator}</i>: #{avalon_item.review_comments.last.comment}".html_safe : '' %></td>
      <td><%= avalon_item.review_comments.size > 0 ? avalon_item.review_comments.last.created_at.strftime("%m/%d/%Y") : '' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/nav/_cm_start.html.erb
<p>Collection Manager Workflow</p>
<div class="rvt-m-all-xxs rvt-border-radius">
  <span>Filters: </span>
  <%= link_to avalon_all_cm_items_path do %>
    <span id="cm_all_badge" class="filter-badge rvt-badge pointer" >All</span>
  <% end %>
  <%= link_to avalon_items_cm_iu_default_only_path do %>
    <span id="cm_default_badge" class="filter-badge rvt-badge <%= action_name == 'cm_iu_default_only' ? 'rvt-badge--info' : 'rvt-badge--info-secondary' %> pointer" >Default Access</span>
  <% end %>
  <%= link_to avalon_items_cm_waiting_on_cl_path do %>
    <span id="cm_review_badge" class="filter-badge rvt-badge <%= action_name == 'cm_waiting_on_cl' ? 'rvt-badge--warning' : 'rvt-badge--warning-secondary' %> pointer" >Review Requested</span>
  <% end %>
  <%= link_to avalon_items_cm_waiting_on_self_path do %>
    <span id="cm_responses_badge" class="filter-badge rvt-badge <%= action_name == 'cm_waiting_on_self' ? 'rvt-badge--danger' : 'rvt-badge--danger-secondary' %> pointer" >Responses</span>
  <% end %>
  <%= link_to avalon_items_cm_access_determined_path do %>
    <span id="cm_determined_badge" class="filter-badge rvt-badge <%= action_name == 'cm_access_determined' ? 'rvt-badge--success' : 'rvt-badge--success-secondary' %> pointer" >Access Determined</span>
  <% end %>
  <%= link_to avalon_items_cm_published_path do %>
    <span id="cm_determined_badge" class="filter-badge rvt-badge <%= action_name == 'cm_published' ? 'filter-badge rvt-badge rvt-badge--info pointer' : "filter-badge rvt-badge rvt-badge--info-secondary pointer" %> pointer" >Published in MCO</span>
  <% end %>
</div>
<div id="results_table_div">
  <%= render partial: 'nav/cm_avalon_items_table' %>
</div>

app/views/nav/date_search.html.erb
<h4>Publication Year Search</h4>
<p>Enter a Start Year to search from that year to present. Enter an End Year to specify a range.</p>
<%= form_tag(date_search_post_path, {method: :post, id: 'date_search_form'}) do %>
  <div class="">
    <label for="start_year" class="rvt-display-inline">Start Year</label>
    <%= text_field_tag :start_year, params[:start_year], {id: "start_year", class: "rvt-input-group__input rvt_display_inline rvt-width-xs year", type: "text", placeholder: 'YYYY'} %>
  </div>
  <div class="">
    <label for="end_year" class="rvt-display-inline">End Year</label>
    <%= text_field_tag :end_year, params[:end_year], {id: "end_year", class: "rvt-input-group__input rvt_display_inline rvt-width-xs year", type: "text", placeholder: 'YYYY'} %>
  </div>
  <div>
    <button class="rvt-button">Search</button>
  </div>
<% end %>
<% if @avalon_items || @works %>
  <h4>Results for <%= params[:start_year] %> - <%= params[:end_year].blank? ? 'present' : params[:end_year] %></h4>

  <div class="rvt-grid rvt-container">
    <div class="rvt-grid__item">
      <h5>Avalon Items</h5>
      <table>
        <tbody>
        <% @avalon_items.each do |ai| %>
          <tr>
            <td><%= link_to "#{ai.title}", avalon_item_path(ai), {target: '_blank'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="rvt-grid__item">
      <h5>Works</h5>
      <table>
        <tbody>
        <% @works.each do |w| %>
        <tr>
          <td><%= link_to "#{w.title}", work_path(w), {target: '_blank'} %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% end %>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(event) {
  	hookYearValidation();
    $('#date_search_form').submit(function() {
    	let s = $('#start_year').text();
    	let e = $('#end_year').text();
    	if (s.length === 0 && e.length === 0) {
    		event.preventDefault();
    		swal({
          title: "Error",
          text: "You must specify at least a start or and end date to search for records"
        });
      } else {

      }
    });
  });
</script>

app/views/nav/no_recording.html.erb
<h4>No Results</h4>
<p>Could not find a recording with MDPI barcode: <%= params[:mdpi_barcode] %></p>

app/views/nav/search.html.erb
<% if @avalon_items.size == 0 %>
  <p class=""> No results found for: <i class=""><b><%= params[:search] %></b></i></p>
<% else %>
  <p class=""> Search results for: <i class=""><b><%= params[:search] %></b></i></p>
<% end %>
<div class="flex_row">
  <div class="column_05">
    <div class="rvt-p-all-xs">
      <span id="ais" class="rvt-badge rvt-badge--info pointer">Avalon Items (<%= @avalon_items.size %>)</span>
    </div>
    <div class="rvt-p-all-xs">
      <span id="ps" class="rvt-badge rvt-badge--info-secondary pointer">People (<%= @people.size %>)</span>
    </div>
    <div class="rvt-p-all-xs">
      <span id="ws" class="rvt-badge rvt-badge--info-secondary pointer">Works (<%= @works.size %>)</span>
    </div>
  </div>
  <div class="column_80">
    <div class="avalon_items <%= "hidden" if @avalon_items.size == 0 && (@people.size > 0 || @works.size > 0) %>">
      <% if @avalon_items.size == 0 %>
      <p>There are no Avalon Items matching your search: <i><%= params[:search] %></i></p>
      <% else %>
        <table id="avalon_items_table" class="rvt-table-compact rvt-table-cells show_me">
          <thead>
          <tr>
            <th class="no_sort">Title</th>
            <th class="no_sort">Access Determination</th>
          </tr>
          </thead>
          <tbody>
          <% @avalon_items.each do |ai| %>
            <tr>
              <th><%= link_to ai.title, avalon_item_path(ai), {target: '_blank'} %></th>
              <th><%= ai.access_determination %></th>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="people <%= "hidden" unless @avalon_items.size == 0 && @people.size > 0 %>">
      <% if @people.size == 0 %>
        <p>There are no People/Entities matching your search: <i><%= params[:search] %></i></p>
      <% else %>
        <table id="people_table" class="rvt-table-compact rvt-table-cells show_me">
          <thead>
          <tr>
            <th class="no_sort">Name/Company Name</th>
            <th class="no_sort">Date of Birth</th>
            <th>Date of Death</th>
          </tr>
          </thead>
          <tbody>
          <% @people.each do |p| %>
          <tr>
            <th><%= link_to "#{p.entity? ? p.company_name : p.full_name}", person_path(p) %></th>
            <th><%= p.date_of_birth_edtf unless (p.entity? || p.date_of_birth_edtf.blank?) %></th>
            <th><%= p.date_of_death_edtf unless (p.entity? || p.date_of_death_edtf.blank?) %></th>
          </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="works <%= "hidden" unless @works.size > 0 && (@avalon_items.size == 0 && @people.size == 0) %>">
      <% if @works.size == 0 %>
        <p>There are no Works matching your search: <i><%= params[:search] %></i></p>
      <% else %>
        <table id="people_table" class="rvt-table-compact rvt-table-cells show_me">
          <thead>
          <tr><th>Title</th></tr>
          </thead>
          <% @works.each do |w| %>
          <tr>
            <th><%= link_to "#{w.title}", work_path(w) %></th>
          </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('.rvt-badge').click(function() {
      let t = $(this)[0];
    	let ais = $('#ais');
      let ps = $('#ps');
      let ws = $('#ws');
      if (t === ais[0]) {
      	$('.people').hide();
        $('.works').hide()
        ais.removeClass('rvt-badge--info-secondary').addClass('rvt-badge--info');
        ps.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
        ws.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
      	$('.avalon_items').show(200)
      } else if (t === ps[0]) {
	      $('.avalon_items').hide();
	      $('.works').hide();
	      ps.removeClass('rvt-badge--info-secondary').addClass('rvt-badge--info');
	      ais.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
	      ws.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
	      $('.people').show(200)
      } else {
	      $('.avalon_items').hide();
	      $('.people').hide();
	      ws.removeClass('rvt-badge--info-secondary').addClass('rvt-badge--info');
	      ps.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
	      ais.removeClass('rvt-badge--info').addClass('rvt-badge--info-secondary');
	      $('.works').show(200);
      }
    })
  })
</script>

app/views/nav/start.html.erb
<% if flash[:warning] || flash.now[:warning] %>
  <p class="warning"><%= flash[:warning].html_safe %></p>
<% end %>

<div class="rvt_container">
  <% if User.copyright_librarian?(User.current_username) %>
    <%= render partial: 'nav/cl_start' %>
  <% else %>
    <%= render partial: 'nav/cm_start' %>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        hookTableSort('avalon_items_table');
    });

    function hookTableSort(tableId) {
        $('#'+tableId).tablesorter(
            {
                theme: 'bootstrap',
                sortList: [[0,0], [1,0]],
                headers: {
                    '.no_sort' : {
                        sorter: false
                    }
            }
        });
    }
</script>

app/views/nav/test.html.erb
<h2>Animated Accordion</h2>
<p>Click on the buttons to open the collapsible content.</p>

<button class="accordion">Section 1</button>
<div class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

<button class="accordion">Section 2</button>
<div class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

<button class="accordion">Section 3</button>
<div id="panel" class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
            }
        });
    }
</script>